# The URL the site will be built for
base_url = "https://blog.cstef.dev"
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
taxonomies = [{ name = "tags" }]
build_search_index = true

[search]
index_format = "fuse_javascript"
include_description = true
include_path = true

[markdown]
render_emoji = true
bottom_footnotes = true

highlight_theme = "css"
highlight_code = true

# highlight_themes_css = [
#     { theme = "gruvbox-dark", filename = "../styles/syntax-theme-dark.css" },
#     { theme = "gruvbox-light", filename = "../styles/syntax-theme-light.css" },
# ]

[markdown.math]
engine = "typst"
svgo = "svgo.config.mjs"
css = "styles/typst-embed.css"
addon = "helpers.typ"
