# The URL the site will be built for
base_url = "https://fr4nk1in.top"
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
taxonomies = [{ name = "tags" }]
build_search_index = true

[search]
index_format = "fuse_javascript"
include_description = true
include_path = true
include_content = false

[markdown]
render_emoji = true
bottom_footnotes = true

highlight_theme = "css"
highlight_code = true

[markdown.math]
engine = "typst"
svgo = "svgo.config.mjs"
css = "styles/typst-embed.css"
addon = "helpers.typ"
