name: Build and Deploy to Cloudflare Pages

on:
    push:
        branches:
            - dev
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Homebrew
              id: set-up-homebrew
              uses: Homebrew/actions/setup-homebrew@master

            - uses: tecolicom/actions-use-homebrew-tools@v1
              with:
                  tools: cestef/tap/zola svgo

            - name: Cache Zola build
              uses: actions/cache@v3
              with:
                  path: |
                      .cache
                      public
                  key: ${{ runner.os }}-zola-${{ hashFiles('**/*.md', 'config.toml', 'templates/**/*') }}
                  restore-keys: |
                      ${{ runner.os }}-zola-

            - name: Build site
              run: zola build

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: site
                  path: public

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: site
                  path: public

            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy public --project-name=blog-cstef-dev
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
