name: Build and Deploy to Cloudflare Pages

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Homebrew
              id: set-up-homebrew
              uses: Homebrew/actions/setup-homebrew@master

            - uses: tecolicom/actions-use-homebrew-tools@v1
              with:
                  tools: cestef/tap/zola svgo

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install

            - name: Cache Zola build
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/zola
                  key: ${{ runner.os }}-zola-${{ hashFiles('**/*.md', 'config.toml', 'templates/**/*') }}
                  restore-keys: |
                      ${{ runner.os }}-zola-

            - name: Build Tailwind CSS
              run: pnpm run css:build

            - name: Build Zola site
              run: zola build

            - name: Display structure of built files
              run: ls -R public
        
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: public

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
